runtime: python37

env_variables:
  GOOGLE_CLIENT_ID: "568005951318-ugbfhrgdbrof3hardna6t40g7296ga61.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "MXyUlgYxlBg9icURpS-ww-s3"
  MONGO_URI: "mongodb+srv://bikefitguru:WnV3lPmYg7Z3W8L6@cluster0-anf6o.gcp.mongodb.net/test"

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto